<a href="https://colab.research.google.com/github/youngseo21/esaa_22/blob/main/%EC%B6%A9%EB%82%A8%EB%B6%80%EB%B6%84%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
chungnam = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/chungnam1.csv")

In [10]:
chungnam.head()

,Unnamed: 0,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state
0,0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남
1,1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남
2,2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남
3,3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남
4,4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남

In [12]:
chungnam.columns

Index(['Unnamed: 0', 'RECV_CPLT_DM', 'NPA_CL', 'EVT_STAT_CD', 'EVT_CL_CD',
       'RPTER_SEX', 'HPPN_PNU_ADDR', 'HPPN_X', 'HPPN_Y', 'SME_EVT_YN', 'ADDR1',
       'state'],
      dtype='object')

In [14]:
chungnam.drop('Unnamed: 0', axis=1, inplace=True)

In [15]:
chungnam.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남

In [16]:
cn = chungnam

In [18]:
cn.ADDR1.value_counts()

충청남도                  106888
[이관주소]충청남도                16
충남                         4
천안시                        2
경부/하행선/천안에서청주내려가는/         1
천안방향                       1
Name: ADDR1, dtype: int64

In [21]:
cn[cn.ADDR1 == '천안시']

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state
40,2020-01-01 08:02:00,19,10,402,1,천안시 동남구 목천면(목천면),127.214763,36.800055,Y,천안시,충남
82465,2021-02-25 20:23:10,19,10,403,1,천안시 서북구 성거읍 요방리(성거읍) 113-7,127.182266,36.854973,unknown,천안시,충남

In [22]:
cn[cn.ADDR1 == '천안방향'] # 삭제

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state
34471,2020-06-22 16:17:15,19,10,401,1,천안방향,127.119863,36.630146,unknown,천안방향,충남

In [23]:
cn.drop([34471], axis=0, inplace=True)

In [24]:
cn[cn.ADDR1 == '경부/하행선/천안에서청주내려가는/'] # 삭제

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state
18674,2020-04-11 12:08:41,19,10,401,1,경부/하행선/천안에서청주내려가는/,127.522742,36.594238,unknown,경부/하행선/천안에서청주내려가는/,충남

In [25]:
cn.drop([18674], axis=0, inplace=True)

In [26]:
cn[cn.ADDR1 == '[이관주소]충청남도']

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state
16465,2020-03-30 11:26:42,19,10,401,1,[이관주소]충청남도 당진시 신평면 운정리 50-1,126.82521,36.88487,unknown,[이관주소]충청남도,충남
28277,2020-05-27 06:50:49,19,10,401,1,[이관주소]충청남도 서천군 화양면 남성리 196-8,126.80684,36.06510,Y,[이관주소]충청남도,충남
28739,2020-05-29 09:45:37,19,10,401,1,[이관주소]충청남도 아산시 배방읍 세교리 373-6,127.10194,36.78416,unknown,[이관주소]충청남도,충남
38437,2020-07-10 09:39:06,19,10,401,1,[이관주소]충청남도 천안시 동남구 광덕면 신흥리 66-1,127.11900,36.70242,unknown,[이관주소]충청남도,충남
39253,2020-07-13 12:53:42,19,10,401,1,[이관주소]충청남도 아산시 둔포면 봉재리 56-7 GPS위,127.04278,36.88666,unknown,[이관주소]충청남도,충남
42845,2020-07-28 23:51:53,19,10,401,2,[이관주소]충청남도 아산시 권곡동 171-14,127.01444,36.79055,Y,[이관주소]충청남도,충남
42846,2020-07-29 00:00:42,19,10,401,2,[이관주소]충청남도 아산시 권곡동 171-14,127.01444,36.79055,Y,[이관주소]충청남도,충남
52083,2020-09-05 23:50:52,19,10,401,1,[이관주소]충청남도 홍성군 갈산면 운곡리 402-1,126.55334,36.61805,unknown,[이관주소]충청남도,충남
53446,2020-09-12 10:03:19,19,10,402,1,[이관주소]충청남도 논산시 은진면 토양리 116-3,127.10154,36.15434,Y,[이관주소]충청남도,충남
53616,2020-09-12 18:43:33,19,10,401,2,[이관주소]충청남도 서산시 운산면 갈산리 724-7,126.56612,36.81250,Y,[이관주소]충청남도,충남
57422,2020-09-27 22:46:30,19,10,406,1,[이관주소]충청남도 천안시 서북구 입장면 가산리 362-7,127.19245,36.94250,unknown,[이관주소]충청남도,충남
60738,2020-10-11 20:55:50,19,10,401,1,[이관주소]충청남도 아산시 둔포면 둔포리 251-8,127.04028,36.93056,unknown,[이관주소]충청남도,충남
63825,2020-10-24 13:17:56,19,10,401,3,[이관주소]충청남도 논산시 취암동 427-4,127.09135,36.19694,unknown,[이관주소]충청남도,충남
67594,2020-11-08 15:48:34,19,10,401,2,[이관주소]충청남도 천안시 동남구 수신면 속창리 179-2,127.27953,36.73351,unknown,[이관주소]충청남도,충남
69529,2020-11-16 13:16:09,19,10,401,1,[이관주소]충청남도 아산시 좌부동 85-10,127.03084,36.75250,unknown,[이관주소]충청남도,충남
69731,2020-11-17 11:36:50,19,10,401,1,[이관주소]충청남도 논산시 부적면 마구평리 37-8 gp,127.13051,36.21395,unknown,[이관주소]충청남도,충남

In [27]:
cn.ADDR1.value_counts()

충청남도          106888
[이관주소]충청남도        16
충남                 4
천안시                2
Name: ADDR1, dtype: int64

In [28]:
def find_add(add):
  words = add.split()
  return len(words)>2

cn['is_add'] = cn.apply(lambda x: find_add(x['HPPN_PNU_ADDR']), axis=1)

In [29]:
cn.is_add.value_counts()

True     106908
False         2
Name: is_add, dtype: int64

In [30]:
cn[cn.is_add == False] # 제거

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,is_add
4445,2020-01-23 13:24:22,19,10,401,1,충청남도 당진시,126.728218,36.981384,unknown,충청남도,충남,False
57862,2020-09-29 13:20:35,13,10,401,2,충청남도 공주시,127.271659,36.361998,unknown,충청남도,충남,False

In [31]:
cn.drop([4445], axis=0, inplace=True)
cn.drop([57862], axis=0, inplace=True)

In [32]:
cn.drop('is_add', axis=1, inplace=True)

In [33]:
cn.ADDR1.value_counts()

충청남도          106886
[이관주소]충청남도        16
충남                 4
천안시                2
Name: ADDR1, dtype: int64

In [34]:
def city(add):
  splitted = add.split()
  if len(splitted) > 1:
    if '천안' in splitted[0]: 
      return '천안시'
    else:
      return splitted[1]
  else:
    return "unknown"

cn['city'] = cn.apply(lambda x: city(x['HPPN_PNU_ADDR']), axis=1)
cn.city.value_counts()

천안시    32142
아산시    15694
당진시     9830
서산시     9081
공주시     6693
보령시     6188
논산시     6037
홍성군     4846
예산군     3910
태안군     3278
서천군     2493
부여군     2457
금산군     2156
청양군     1110
계룡시      985
당진군        8
Name: city, dtype: int64

In [36]:
cn[cn.city=='천안시'].HPPN_PNU_ADDR

2              충청남도 천안시 서북구 불당동(불당동) 204-4
3         충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19
6              충청남도 천안시 동남구 안서동(신안동) 159-7
9              충청남도 천안시 동남구 신방동(신방동) 71-23
14             충청남도 천안시 동남구 봉명동(봉명동) 206-7
                        ...
106894         충청남도 천안시 서북구 성정동(성정2동) 1536
106898          충청남도 천안시 동남구 신방동 (신방동) 870
106899    충청남도 천안시 서북구 성거읍 요방리(성거읍) 160-22
106906         충청남도 천안시 동남구 봉명동(봉명동) 67-13
106908     충청남도 천안시 동남구 성남면 석곡리(성남면) 346-2
Name: HPPN_PNU_ADDR, Length: 32142, dtype: object

In [38]:
cn[cn.city=='당진군'].HPPN_PNU_ADDR

6056       충청남도 당진군 송악면 복운리
7887       충청남도 당진군 면천면 자개리
12510      충청남도 당진군 면천면 자개리
23806      충청남도 당진군 면천면 자개리
23937      충청남도 당진군 면천면 자개리
44694     충청남도 당진군 당진읍 사기소리
56562    충청남도 당진군 당진읍 사기소리
80880    충청남도 당진군 당진읍 사기소리
Name: HPPN_PNU_ADDR, dtype: object

In [46]:
def town(add):
  splitted = add.split()
  if len(splitted) > 1:
    if '천안' in splitted[0]: 
      return splitted[2]
    elif '천안' in splitted[1]:
      if '동남' in splitted[2]:
        return splitted[3]
      elif '서북' in splitted[2]:
        return splitted[3]
      else:
        return splitted[2]
    else:
      return splitted[2]
  else:
    return "unknown"

cn['town'] = cn.apply(lambda x: town(x['HPPN_PNU_ADDR']), axis=1)

In [48]:
cn['town'].unique() # 미친

array(['정안면', '채운면', '불당동(불당동)', '목천읍', '읍내동(부춘동)', '우두동(당진3동)',
       '안서동(신안동)', '탕정면', '신방동(신방동)', '석문면', '홍성읍', '광석면', '웅진동(웅진동)',
       '봉명동(봉명동)', '성정동(성정2동)', '성정동', '삼룡동(청룡동)', '두정동(부성2동)',
       '신흑동(대천5동)', '신흑동', '신관동(신관동)', '홍산면', '홍북읍', '문화동(문성동)', '수신면',
       '석남동(석남동)', '성주면', '유구읍', '응봉면', '목천면(목천면)', '직산읍', '명천동(대천4동)',
       '송산면', '서면', '쌍용동(쌍용1동)', '봉명동', '초촌면', '석림동(수석동)', '안면읍', '지곡면',
       '목면', '팔봉면', '우강면', '죽정동(대천1동)', '운산면', '신암면', '도고면', '해미면',
       '두정동(부성1동)', '남포면', '서천읍', '합덕읍', '대천동(대천2동)', '와촌동(봉명동)', '동대동',
       '동대동(대천3동)', '천북면', '온천동(온양2동)', '강경읍', '산성동(웅진동)', '덕산면', '둔포면',
       '고북면', '읍내동(당진1동)', '신도안면', '신창면', '삽교읍', '청수동(청룡동)', '계룡면', '신양면',
       '노성면(노성면)', '배방읍', '신평면', '태안읍', '복수면', '부석면', '취암동(취암동)', '정미면',
       '반포면', '벌곡면', '연산면', '성남면', '동문동(동문1동)', '금산읍', '용화동(온양5동)', '송악읍',
       '주교면', '성정동(성정1동)', '신부동', '대산읍', '음봉면', '월송동(월송동)', '다가동(일봉동)',
       '신부동(신안동)', '지산동(취암동)', '성성동(부성2동)', '강산동(부창동)', '동대동(대천2동)',
       '좌부동(온양6동)', '성거읍', '채운동(당진2동)', '원당동(당진3동)', '강산동', '궁촌동(대천4동)',
       '병천면', '권곡동(온양3동)', '쌍용동(봉명동)', '쌍용동(쌍용3동)', '부여읍', '내동(취암동)',
       '홍북면', '수청동(당진1동)', '예산읍', '용곡동(일봉동)', '대술면', '예천동(석남동)', '금마면',
       '인주면', '웅천읍', '군북면', '모종동(온양3동)', '구성동(청룡동)', '차암동(부성2동)', '연무읍',
       '광천읍', '화양면', '화지동(취암동)', '음암면', '성정동(부성1동)', '온천동(온양1동)',
       '잠홍동(동문1동)', '쌍용동(쌍용2동)', '청양읍', '우성면', '청소면', '금학동(금학동)',
       '대흥동(중앙동)', '북면', '중동(중학동)', '백석동(백석동)', '내동', '금성면', '인지면', '성환읍',
       '반월동(취암동)', '방축동(온양4동)', '염치읍', '남곡동(대천5동)', '구룡동(청룡동)',
       '수석동(수석동)', '차암동', '순성면', '풍기동(온양6동)', '신방동', '읍내동', '금흥동(월송동)',
       '성연면', '추부면', '구항면', '송악면', '서부면', '규암면', '장항읍', '풍세면',
       '동대동(대천4동)', '성황동(문성동)', '양촌면', '원성동', '원성동(원성2동)', '구성동', '쌍용동',
       '화성면', '주포면', '대교동(부창동)', '면천면', '취암동', '입장면', '영인면', '정산면',
       '원성동(원성1동)', '명천동', '광덕면', '부창동(부창동)', '동문동(동문2동)', '갈산면', '은하면',
       '장암면', '청당동(청룡동)', '가야곡면', '엄사면', '권곡동', '금암동(금암동)', '옥룡동(옥룡동)',
       '비인면', '부적면', '신당동(부성1동)', '월미동(신관동)', '내항동', '수청동', '마서면',
       '배미동(온양4동)', '두정동', '배미동', '법곡동(온양6동)', '남양면', '석성면', '오천면', '봉산면',
       '비봉면', '한산면', '금흥동', '내항동(대천5동)', '중학동(중학동)', '온천동', '제원면', '은진면',
       '두마면', '채운동', '진산면', '오가면', '풍기동', '용곡동(신방동)', '용곡동', '동면', '우두동',
       '근흥면', '주산면', '행정동', '행정동(당진2동)', '영성동(중앙동)', '운곡면', '청당동',
       '오룡동(중앙동)', '시곡동(당진3동)', '은산면', '시곡동', '실옥동(온양4동)', '기산동(온양5동)',
       '남면', '옥산면', '모종동', '동문동', '궁촌동', '성황동', '화산동(대천3동)', '금성동(웅진동)',
       '명천동(대천3동)', '예천동(부춘동)', '대덕동(당진2동)', '금암동', '관촉동', '사직동(중앙동)',
       '상왕동(옥룡동)', '탄천면', '원당동', '불당동', '결성면', '의당면', '송선동', '백석동',
       '동현동(월송동)', '대덕동', '장존동(온양6동)', '소원면', '구룡면', '득산동(온양4동)', '남일면',
       '대치면', '상월면', '청남면', '면천면(면천면)', '신풍면', '잠홍동', '원북면', '신기동(옥룡동)',
       '신기동', '외산면', '법곡동(온양5동)', '고대면', '반죽동(중학동)', '선장면', '성성동', '안서동',
       '사곡면', '다가동', '구룡동', '부대동(부성1동)', '문화동', '고덕면', '임천면', '용화동',
       '이원면', '대천동(대천4동)', '대호지면', '예천동', '이인면', '초사동(온양5동)', '기산면',
       '지산동', '실옥동(온양1동)', '대흥면', '관촉동(취암동)', '읍내동(온양6동)', '신관동', '영성동',
       '부리면', '대흥동', '광시면', '노성면', '석문면(송산면)', '대천동', '송선동(월송동)',
       '봉황동(중학동)', '시초면', '반월동', '고남면', '업성동(부성1동)', '석림동', '미산면',
       '남동(온양6동)', '갈산동(부춘동)', '성동면', '사기소동(당진2동)', '대천동(대천5동)',
       '등화동(부창동)', '판교면', '대교동', '대천동(대천3동)', '청수동', '종천면', '석남동',
       '덕지동(취암동)', '홍동면', '부여읍(부여읍)', '마산면', '유량동(원성1동)', '요암동(대천5동)',
       '청라면', '석장리동', '세도면', '청룡동', '초사동', '내산면', '남이면', '태봉동(금학동)',
       '대교동(취암동)', '화지동(부창동)', '사직동', '구룡동(당진2동)', '죽성동', '삼룡동', '장존동',
       '봉정동(금학동)', '산성동', '장동(석남동)', '무릉동(월송동)', '방축동', '금성동', '검상동(금학동)',
       '금성면(금성면)', '금학동', '장곡면', '실옥동', '옥룡동', '부대동', '석장리동(월송동)', '쌍신동',
       '교동(웅진동)', '죽성동(석남동)', '소학동(옥룡동)', '덕지천동', '덕지천동(석남동)', '장평면',
       '대천동(대천1동)', '소학동', '죽정동', '덕지동', '신인동(온양5동)', '용연동(당진2동)',
       '신동(배방읍)', '검상동', '수석동', '법곡동(온양3동)', '쌍신동(신관동)', '양화면',
       '양대동(석남동)', '신동', '신동(온양3동)', '안서동(안서동)', '득산동', '갈산동', '사기소동',
       '월송동(신관동)', '온석동(동문1동)', '오곡동(금학동)', '오곡동', '주미동(금학동)',
       '와촌동(성정1동)', '신당동', '중동', '문산면', '점양동(온양4동)', '월송동', '유량동', '웅진동',
       '부창동', '온석동', '염치읍(온양4동)', '상왕동', '충화면', '성동면(성동면)', '남곡동',
       '운산면(운산면)', '좌부동', '강경읍(강경읍)', '입장면(입장면)', '대산읍(대산읍)', '봉황동',
       '용연동', '요암동', '반죽동', '용화동(온양6동)', '업성동', '고대면(고대면)', '신창면(신창면)',
       '백석동(불당동)', '오룡동', '와촌동', '중학동', '신방동신방동', '죽정동행정대천1동',
       '성정동행정성정2동', '읍내동당진1동', '삼룡동청룡동', '신관동행정신관동', '수청동당진1동',
       '원성동행정원성2동', '남곡동행정대천5동', '봉명동행정봉명동', '모종동행정온양3동', '화산동행정대천3동',
       '읍내동행정부춘동', '성성동부성2동', '두정동행정부성2동', '화산동대천3동', '성정동행정성정1동',
       '대천동행정대천2동', '궁촌동행정대천4동', '청당동행정청룡동', '반월동행정취암동', '신당동부성1동',
       '시곡동행정당진3동', '동대동행정대천3동', '용화동행정온양5동', '두정동부성1동', '불당동행정불당동',
       '쌍용동행정쌍용3동', '다가동일봉동', '두정동행정부성1동', '성정동성정2동', '다가동행정일봉동',
       '불당동불당동', '지산동취암동', '풍기동행정온양6동', '사직동중앙동', '권곡동온양3동', '석남동행정석남동',
       '영성동행정중앙동', '쌍용동행정쌍용2동', '구성동청룡동', '소학동행정옥룡동', '산성동행정웅진동',
       '쌍용동행정쌍용1동', '대천동대천2동', '옥룡동옥룡동', '원당동당진3동', '권곡동행정온양3동',
       '중학동행정중학동', '예천동행정석남동', '석림동행정수석동', '중동중학동', '강산동부창동', '부창동부창동',
       '동대동대천3동', '성정동성정1동', '동문동행정동문1동', '원성동원성2동', '신부동행정신안동',
       '사직동행정중앙동', '쌍용동쌍용1동', '신방동행정신방동', '원성동행정원성1동', '방축동행정온양4동',
       '두정동부성2동', '풍기동온양6동', '읍내동행정당진1동', '구룡동청룡동', '백석동행정백석동', '시곡동당진3동',
       '대흥동행정중앙동', '검상동행정금학동', '백석동백석동', '월송동행정월송동', '구성동행정청룡동',
       '용화동온양5동', '예천동석남동', '석림동수석동', '대교동행정부창동', '삼룡동행정청룡동', '채운동당진2동',
       '금성동웅진동', '문화동문성동', '동문동행정동문2동', '실옥동행정온양4동', '청당동청룡동', '반죽동행정중학동',
       '점양동온양4동', '강산동행정부창동', '와촌동행정봉명동', '모종동온양3동', '차암동행정부성2동',
       '옥룡동행정옥룡동', '내동행정취암동', '온천동온양1동', '온천동행정온양2동', '수석동행정수석동',
       '온천동행정온양1동', '용곡동행정일봉동', '취암동행정취암동', '취암동취암동', '신부동신안동',
       '신흑동행정대천5동', '신흑동대천5동', '좌부동온양6동', '봉명동봉명동', '동문동동문1동', '문화동행정문성동',
       '신관동신관동', '읍내동부춘동', '금흥동행정월송동', '실옥동행정온양1동', '원성동원성1동',
       '성성동행정부성2동', '대천동행정대천3동', '법곡동행정온6동', '온천동온양2동', '채운동행정당진2동',
       '금암동금암동', '기산동온양5동', '쌍용동쌍용3동', '신당동행정부성1동', '명천동행정대천4동',
       '양대동행정석남동', '청수동행정청룡동', '화지동행정취암동', '차암동부성2동', '실옥동온양4동',
       '대천동행정대천4동', '남곡동대천5동', '내동취암동', '원당동행정당진3동', '잠홍동행정동문1동',
       '잠홍동동문1동', '득산동온양4동', '장존동행정온양6동', '부창동행정부창동', '득산동행정온양4동',
       '쌍용동쌍용2동', '동문동동문2동', '등화동행정부창동', '등화동', '중동행정중학동', '와촌동봉명동',
       '금성동행정웅진동', '갈산동부춘동', '산성동웅진동', '읍내동행정온양6동', '웅진동행정웅진동', '장존동온양6동',
       '금암동행정금암동', '취암동(부적면)', '태봉동', '오남동(석남동)', '온천동(온양5동)', '기산동',
       '0-0', '화지동', '차암동(부성1동)', '신인동', '당진읍', '대흥동(봉명동)', '화산동',
       '구룡동(목천읍)', '월미동', '동현동', '문화동(중앙동)', '영성동(원성2동)', '이원면(이원면)',
       '제원면(제원면)', '봉정동', '불당동(백석동)', '주미동', '성환읍(성환읍)', '남이면(남이면)',
       '탕정면(탕정면)', '팔봉면(팔봉면)', '신방동(쌍용2동)', '주산면(주산면)', '성남면(성남면)',
       '소원면(소원면)', '광석면(광석면)', '성황동(신안동)', '원성1동', '법곡동', '장동',
       '정산면(정산면)', '점양동', '교동', '남동', '양대동', '충청남도', '오남동'], dtype=object)

In [49]:
cn[cn.town=='0-0'] #제거

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2
42336,2020-07-26 17:39:45,19,10,401,3,충청남도 계룡시 0-0 신풍주차장 7KM로 남은 지점(대전~서산방향),127.03401,36.48962,N,충청남도,충남,계룡시,0-0,0-0

In [50]:
cn.drop([42336], axis=0, inplace=True)

In [51]:
# town안의 괄호 제거
import re

def bracket(town):
  result = re.sub(r'\([^)]*\)', '', town)
  return result

cn['town2'] = cn.apply(lambda x: bracket(x['town']), axis=1)
cn.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남,공주시,정안면,정안면
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남,논산시,채운면,채운면
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남,천안시,불당동(불당동),불당동
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남,천안시,목천읍,목천읍
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남,서산시,읍내동(부춘동),읍내동

In [52]:
cn.town2.unique()

array(['정안면', '채운면', '불당동', '목천읍', '읍내동', '우두동', '안서동', '탕정면', '신방동',
       '석문면', '홍성읍', '광석면', '웅진동', '봉명동', '성정동', '삼룡동', '두정동', '신흑동',
       '신관동', '홍산면', '홍북읍', '문화동', '수신면', '석남동', '성주면', '유구읍', '응봉면',
       '목천면', '직산읍', '명천동', '송산면', '서면', '쌍용동', '초촌면', '석림동', '안면읍',
       '지곡면', '목면', '팔봉면', '우강면', '죽정동', '운산면', '신암면', '도고면', '해미면',
       '남포면', '서천읍', '합덕읍', '대천동', '와촌동', '동대동', '천북면', '온천동', '강경읍',
       '산성동', '덕산면', '둔포면', '고북면', '신도안면', '신창면', '삽교읍', '청수동', '계룡면',
       '신양면', '노성면', '배방읍', '신평면', '태안읍', '복수면', '부석면', '취암동', '정미면',
       '반포면', '벌곡면', '연산면', '성남면', '동문동', '금산읍', '용화동', '송악읍', '주교면',
       '신부동', '대산읍', '음봉면', '월송동', '다가동', '지산동', '성성동', '강산동', '좌부동',
       '성거읍', '채운동', '원당동', '궁촌동', '병천면', '권곡동', '부여읍', '내동', '홍북면',
       '수청동', '예산읍', '용곡동', '대술면', '예천동', '금마면', '인주면', '웅천읍', '군북면',
       '모종동', '구성동', '차암동', '연무읍', '광천읍', '화양면', '화지동', '음암면', '잠홍동',
       '청양읍', '우성면', '청소면', '금학동', '대흥동', '북면', '중동', '백석동', '금성면', '인지면',
       '성환읍', '반월동', '방축동', '염치읍', '남곡동', '구룡동', '수석동', '순성면', '풍기동',
       '금흥동', '성연면', '추부면', '구항면', '송악면', '서부면', '규암면', '장항읍', '풍세면',
       '성황동', '양촌면', '원성동', '화성면', '주포면', '대교동', '면천면', '입장면', '영인면',
       '정산면', '광덕면', '부창동', '갈산면', '은하면', '장암면', '청당동', '가야곡면', '엄사면',
       '금암동', '옥룡동', '비인면', '부적면', '신당동', '월미동', '내항동', '마서면', '배미동',
       '법곡동', '남양면', '석성면', '오천면', '봉산면', '비봉면', '한산면', '중학동', '제원면',
       '은진면', '두마면', '진산면', '오가면', '동면', '근흥면', '주산면', '행정동', '영성동',
       '운곡면', '오룡동', '시곡동', '은산면', '실옥동', '기산동', '남면', '옥산면', '화산동',
       '금성동', '대덕동', '관촉동', '사직동', '상왕동', '탄천면', '결성면', '의당면', '송선동',
       '동현동', '장존동', '소원면', '구룡면', '득산동', '남일면', '대치면', '상월면', '청남면',
       '신풍면', '원북면', '신기동', '외산면', '고대면', '반죽동', '선장면', '사곡면', '부대동',
       '고덕면', '임천면', '이원면', '대호지면', '이인면', '초사동', '기산면', '대흥면', '부리면',
       '광시면', '봉황동', '시초면', '고남면', '업성동', '미산면', '남동', '갈산동', '성동면',
       '사기소동', '등화동', '판교면', '종천면', '덕지동', '홍동면', '마산면', '유량동', '요암동',
       '청라면', '석장리동', '세도면', '청룡동', '내산면', '남이면', '태봉동', '죽성동', '봉정동',
       '장동', '무릉동', '검상동', '장곡면', '쌍신동', '교동', '소학동', '덕지천동', '장평면',
       '신인동', '용연동', '신동', '양화면', '양대동', '온석동', '오곡동', '주미동', '문산면',
       '점양동', '충화면', '신방동신방동', '죽정동행정대천1동', '성정동행정성정2동', '읍내동당진1동',
       '삼룡동청룡동', '신관동행정신관동', '수청동당진1동', '원성동행정원성2동', '남곡동행정대천5동',
       '봉명동행정봉명동', '모종동행정온양3동', '화산동행정대천3동', '읍내동행정부춘동', '성성동부성2동',
       '두정동행정부성2동', '화산동대천3동', '성정동행정성정1동', '대천동행정대천2동', '궁촌동행정대천4동',
       '청당동행정청룡동', '반월동행정취암동', '신당동부성1동', '시곡동행정당진3동', '동대동행정대천3동',
       '용화동행정온양5동', '두정동부성1동', '불당동행정불당동', '쌍용동행정쌍용3동', '다가동일봉동',
       '두정동행정부성1동', '성정동성정2동', '다가동행정일봉동', '불당동불당동', '지산동취암동',
       '풍기동행정온양6동', '사직동중앙동', '권곡동온양3동', '석남동행정석남동', '영성동행정중앙동',
       '쌍용동행정쌍용2동', '구성동청룡동', '소학동행정옥룡동', '산성동행정웅진동', '쌍용동행정쌍용1동',
       '대천동대천2동', '옥룡동옥룡동', '원당동당진3동', '권곡동행정온양3동', '중학동행정중학동',
       '예천동행정석남동', '석림동행정수석동', '중동중학동', '강산동부창동', '부창동부창동', '동대동대천3동',
       '성정동성정1동', '동문동행정동문1동', '원성동원성2동', '신부동행정신안동', '사직동행정중앙동',
       '쌍용동쌍용1동', '신방동행정신방동', '원성동행정원성1동', '방축동행정온양4동', '두정동부성2동',
       '풍기동온양6동', '읍내동행정당진1동', '구룡동청룡동', '백석동행정백석동', '시곡동당진3동',
       '대흥동행정중앙동', '검상동행정금학동', '백석동백석동', '월송동행정월송동', '구성동행정청룡동',
       '용화동온양5동', '예천동석남동', '석림동수석동', '대교동행정부창동', '삼룡동행정청룡동', '채운동당진2동',
       '금성동웅진동', '문화동문성동', '동문동행정동문2동', '실옥동행정온양4동', '청당동청룡동', '반죽동행정중학동',
       '점양동온양4동', '강산동행정부창동', '와촌동행정봉명동', '모종동온양3동', '차암동행정부성2동',
       '옥룡동행정옥룡동', '내동행정취암동', '온천동온양1동', '온천동행정온양2동', '수석동행정수석동',
       '온천동행정온양1동', '용곡동행정일봉동', '취암동행정취암동', '취암동취암동', '신부동신안동',
       '신흑동행정대천5동', '신흑동대천5동', '좌부동온양6동', '봉명동봉명동', '동문동동문1동', '문화동행정문성동',
       '신관동신관동', '읍내동부춘동', '금흥동행정월송동', '실옥동행정온양1동', '원성동원성1동',
       '성성동행정부성2동', '대천동행정대천3동', '법곡동행정온6동', '온천동온양2동', '채운동행정당진2동',
       '금암동금암동', '기산동온양5동', '쌍용동쌍용3동', '신당동행정부성1동', '명천동행정대천4동',
       '양대동행정석남동', '청수동행정청룡동', '화지동행정취암동', '차암동부성2동', '실옥동온양4동',
       '대천동행정대천4동', '남곡동대천5동', '내동취암동', '원당동행정당진3동', '잠홍동행정동문1동',
       '잠홍동동문1동', '득산동온양4동', '장존동행정온양6동', '부창동행정부창동', '득산동행정온양4동',
       '쌍용동쌍용2동', '동문동동문2동', '등화동행정부창동', '중동행정중학동', '와촌동봉명동', '금성동행정웅진동',
       '갈산동부춘동', '산성동웅진동', '읍내동행정온양6동', '웅진동행정웅진동', '장존동온양6동', '금암동행정금암동',
       '오남동', '당진읍', '원성1동', '충청남도'], dtype=object)

In [58]:
def above_three(town):
  return len(town)>3
cn['is_town'] = cn.apply(lambda x: above_three(x['town2']), axis=1)
cn['is_town'].value_counts()

False    105882
True       1025
Name: is_town, dtype: int64

In [62]:
def count_word(town):
  return len(town)
cn['word_town'] = cn.apply(lambda x: count_word(x['town2']), axis=1)
cn['word_town'].value_counts()

3    103994
2      1888
4       422
9       242
8       174
7       101
6        84
5         2
Name: word_town, dtype: int64

In [60]:
cn[cn['is_town']==True].town2.unique()

array(['신도안면', '가야곡면', '대호지면', '사기소동', '석장리동', '덕지천동', '신방동신방동',
       '죽정동행정대천1동', '성정동행정성정2동', '읍내동당진1동', '삼룡동청룡동', '신관동행정신관동',
       '수청동당진1동', '원성동행정원성2동', '남곡동행정대천5동', '봉명동행정봉명동', '모종동행정온양3동',
       '화산동행정대천3동', '읍내동행정부춘동', '성성동부성2동', '두정동행정부성2동', '화산동대천3동',
       '성정동행정성정1동', '대천동행정대천2동', '궁촌동행정대천4동', '청당동행정청룡동', '반월동행정취암동',
       '신당동부성1동', '시곡동행정당진3동', '동대동행정대천3동', '용화동행정온양5동', '두정동부성1동',
       '불당동행정불당동', '쌍용동행정쌍용3동', '다가동일봉동', '두정동행정부성1동', '성정동성정2동',
       '다가동행정일봉동', '불당동불당동', '지산동취암동', '풍기동행정온양6동', '사직동중앙동', '권곡동온양3동',
       '석남동행정석남동', '영성동행정중앙동', '쌍용동행정쌍용2동', '구성동청룡동', '소학동행정옥룡동',
       '산성동행정웅진동', '쌍용동행정쌍용1동', '대천동대천2동', '옥룡동옥룡동', '원당동당진3동',
       '권곡동행정온양3동', '중학동행정중학동', '예천동행정석남동', '석림동행정수석동', '중동중학동', '강산동부창동',
       '부창동부창동', '동대동대천3동', '성정동성정1동', '동문동행정동문1동', '원성동원성2동', '신부동행정신안동',
       '사직동행정중앙동', '쌍용동쌍용1동', '신방동행정신방동', '원성동행정원성1동', '방축동행정온양4동',
       '두정동부성2동', '풍기동온양6동', '읍내동행정당진1동', '구룡동청룡동', '백석동행정백석동', '시곡동당진3동',
       '대흥동행정중앙동', '검상동행정금학동', '백석동백석동', '월송동행정월송동', '구성동행정청룡동',
       '용화동온양5동', '예천동석남동', '석림동수석동', '대교동행정부창동', '삼룡동행정청룡동', '채운동당진2동',
       '금성동웅진동', '문화동문성동', '동문동행정동문2동', '실옥동행정온양4동', '청당동청룡동', '반죽동행정중학동',
       '점양동온양4동', '강산동행정부창동', '와촌동행정봉명동', '모종동온양3동', '차암동행정부성2동',
       '옥룡동행정옥룡동', '내동행정취암동', '온천동온양1동', '온천동행정온양2동', '수석동행정수석동',
       '온천동행정온양1동', '용곡동행정일봉동', '취암동행정취암동', '취암동취암동', '신부동신안동',
       '신흑동행정대천5동', '신흑동대천5동', '좌부동온양6동', '봉명동봉명동', '동문동동문1동', '문화동행정문성동',
       '신관동신관동', '읍내동부춘동', '금흥동행정월송동', '실옥동행정온양1동', '원성동원성1동',
       '성성동행정부성2동', '대천동행정대천3동', '법곡동행정온6동', '온천동온양2동', '채운동행정당진2동',
       '금암동금암동', '기산동온양5동', '쌍용동쌍용3동', '신당동행정부성1동', '명천동행정대천4동',
       '양대동행정석남동', '청수동행정청룡동', '화지동행정취암동', '차암동부성2동', '실옥동온양4동',
       '대천동행정대천4동', '남곡동대천5동', '내동취암동', '원당동행정당진3동', '잠홍동행정동문1동',
       '잠홍동동문1동', '득산동온양4동', '장존동행정온양6동', '부창동행정부창동', '득산동행정온양4동',
       '쌍용동쌍용2동', '동문동동문2동', '등화동행정부창동', '중동행정중학동', '와촌동봉명동', '금성동행정웅진동',
       '갈산동부춘동', '산성동웅진동', '읍내동행정온양6동', '웅진동행정웅진동', '장존동온양6동', '금암동행정금암동',
       '원성1동', '충청남도'], dtype=object)

In [71]:
cn[cn.word_town==4].town2.unique() # 통과

array(['신도안면', '가야곡면', '대호지면', '사기소동', '석장리동', '덕지천동', '원성1동'],
      dtype=object)

In [72]:
cn.word_town.value_counts()

3    103995
2      1888
4       421
9       242
8       174
7       101
6        84
5         2
Name: word_town, dtype: int64

In [80]:
cn[cn.word_town==5].town2.unique()

array(['중동중학동', '취암동'], dtype=object)

In [84]:
cn[cn.word_town==2].town2.unique()

array(['서면', '목면', '취암동', '북면', '중학동', '동면', '남면', '남동', '장동', '교동', '신동'],
      dtype=object)

In [77]:
cn['town2'] = cn['town2'].replace('내동', '취암동')

In [79]:
cn['town2'] = cn['town2'].replace('내동취암동', '취암동')

In [83]:
cn['town2'] = cn['town2'].replace('중동중학동', '중학동')
cn['town2'] = cn['town2'].replace('중동', '중학동')

In [82]:
cn[cn.town2=='중학동']

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2,is_town,word_town
629,2020-01-04 12:41:34,19,10,402,1,충청남도 공주시 중학동(중학동) 143-12,127.123647,36.448676,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
1318,2020-01-07 22:01:26,19,10,401,1,충청남도 공주시 중학동(중학동) 141-2,127.124476,36.448742,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
1908,2020-01-10 22:18:44,19,10,401,3,충청남도 공주시 중학동(중학동) 9-6,127.125119,36.449315,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
3870,2020-01-20 22:47:39,19,10,401,1,충청남도 공주시 중학동(중학동) 167-63,127.125040,36.445796,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
6807,2020-02-05 12:24:45,19,10,401,1,충청남도 공주시 중학동(중학동) 244-3,127.121338,36.446011,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
16780,2020-04-01 11:15:54,19,10,401,2,충청남도 공주시 중학동(중학동) 137-36,127.124195,36.447732,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
20370,2020-04-20 12:33:23,19,10,401,2,충청남도 공주시 중학동(중학동) 9-20,127.125836,36.449605,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
21788,2020-04-27 18:05:53,19,10,401,1,충청남도 공주시 중학동(중학동) 15,127.125463,36.450588,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
27974,2020-05-25 17:18:03,19,10,401,1,충청남도 공주시 중학동(중학동) 183-1,127.123669,36.445749,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
28568,2020-05-28 14:57:55,19,10,401,1,충청남도 공주시 중학동(중학동) 167-10,127.124318,36.446452,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
30077,2020-06-04 08:43:41,19,10,401,1,충청남도 공주시 중학동(중학동) 9-35,127.125850,36.449354,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
30624,2020-06-06 11:48:43,19,10,401,1,충청남도 공주시 중학동(중학동) 251-35,127.123853,36.450974,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
31329,2020-06-09 14:52:10,19,10,401,3,충청남도 공주시 중학동 137-1,127.121540,36.447240,N,충청남도,충남,공주시,중학동,중학동,False,3
40099,2020-07-17 08:25:14,19,10,402,2,충청남도 공주시 중학동(중학동) 137-1,127.122897,36.447482,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
41292,2020-07-22 16:07:18,19,10,401,1,충청남도 공주시 중학동(중학동) 240-5,127.121108,36.446772,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
43285,2020-07-30 17:54:08,19,10,401,1,충청남도 공주시 중학동(중학동) 255,127.121264,36.447030,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
46041,2020-08-11 22:02:33,19,10,406,1,충청남도 공주시 중학동(중학동) 199-1,127.123413,36.448571,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
47026,2020-08-15 17:34:49,19,10,401,1,충청남도 공주시 중학동(중학동) 240-5,127.120924,36.446611,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
49826,2020-08-27 07:11:15,19,10,401,3,충청남도 공주시 중학동 255 금학동 방향 / 공주고 앞,127.121280,36.447170,N,충청남도,충남,공주시,중학동,중학동,False,3
58233,2020-09-30 17:07:58,19,10,401,1,충청남도 공주시 중학동(중학동) 181,127.123908,36.445596,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
66367,2020-11-03 17:57:32,19,10,401,1,충청남도 공주시 중학동(중학동) 189,127.123333,36.445833,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
69132,2020-11-14 19:49:45,19,10,401,3,충청남도 공주시 중학동 222-1 GPS,127.123600,36.450830,N,충청남도,충남,공주시,중학동,중학동,False,3
71306,2020-12-03 16:30:30,19,10,401,3,충청남도 공주시 중학동 201-11 공주고등학교 앞,127.123340,36.449440,N,충청남도,충남,공주시,중학동,중학동,False,3
74410,2020-12-25 15:27:50,19,10,401,1,충청남도 공주시 중학동(중학동) 184-10,127.123418,36.445747,unknown,충청남도,충남,공주시,중학동(중학동),중학동,False,3
89439,2021-04-11 13:22:44,19,10,401,2,충청남도 공주시 중학동 (중학동) 248-16,127.120870,36.445287,unknown,충청남도,충남,공주시,중학동,중학동,False,3
92013,2021-04-26 20:27:50,19,10,401,1,충청남도 공주시 중학동 (중학동) 47-1,127.123974,36.450427,unknown,충청남도,충남,공주시,중학동,중학동,False,3
93205,2021-05-04 15:37:49,19,10,402,1,충청남도 공주시 중학동 (중학동) 199-1,127.123413,36.448571,unknown,충청남도,충남,공주시,중학동,중학동,False,3
95687,2021-05-19 00:27:20,19,10,401,1,충청남도 공주시 중학동(중학동) 167-26,127.124884,36.446038,Y,충청남도,충남,공주시,중학동(중학동),중학동,False,3
95724,2021-05-19 05:20:27,19,10,401,1,충청남도 공주시 중학동 (중학동) 167-25,127.124935,36.446145,Y,충청남도,충남,공주시,중학동,중학동,False,3
96793,2021-05-25 15:42:54,19,10,401,1,충청남도 공주시 중학동 (중학동) 201-11,127.123234,36.449398,unknown,충청남도,충남,공주시,중학동,중학동,False,3
98165,2021-06-02 03:50:26,19,10,406,1,충청남도 공주시 중학동 (중학동) 199-1,127.123385,36.448185,unknown,충청남도,충남,공주시,중학동,중학동,False,3
106790,2021-07-18 10:00:23,19,10,401,1,충청남도 공주시 중학동 (중학동) 110,127.124942,36.448450,Y,충청남도,충남,공주시,중학동,중학동,False,3

In [63]:
cn[cn.town2=='충청남도']

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2,is_town,word_town
98920,2021-06-05 20:00:30,19,10,401,2,충청남도 홍성군 충청남도 홍성군 금마면,126.73051,36.608102,unknown,충청남도,충남,홍성군,충청남도,충청남도,True,4

In [64]:
cn.at[98920, 'town2'] = '금마면'
cn.at[98920, 'is_town'] = False
cn.at[98920, 'word_town'] = 3

In [89]:
cn.word_town.value_counts()

3    103995
2      1888
4       421
9       242
8       174
7       101
6        84
5         2
Name: word_town, dtype: int64

In [115]:
cn[cn.word_town==4].town2.unique()

array(['신도안면', '가야곡면', '대호지면', '사기소동', '석장리동', '덕지천동', '원성1동'],
      dtype=object)

In [97]:
cn[cn.word_town==6].town2.unique()

array(['신방동신방동', '삼룡동청룡동', '다가동일봉동', '불당동불당동', '지산동취암동', '사직동중앙동',
       '구성동청룡동', '옥룡동옥룡동', '강산동부창동', '부창동부창동', '구룡동청룡동', '백석동백석동',
       '예천동석남동', '석림동수석동', '금성동웅진동', '문화동문성동', '청당동청룡동', '취암동취암동',
       '신부동신안동', '봉명동봉명동', '신관동신관동', '읍내동부춘동', '금암동금암동', '와촌동봉명동',
       '갈산동부춘동', '산성동웅진동'], dtype=object)

In [109]:
cn[cn.town2=='청룡동']

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2,is_town,word_town
4488,2020-01-23 15:07:14,19,10,403,1,충청남도 천안시 동남구 청룡동,127.173042,36.786983,unknown,충청남도,충남,천안시,청룡동,청룡동,False,3
5035,2020-01-25 19:13:31,19,10,403,1,충청남도 천안시 동남구 청룡동,127.173042,36.786983,unknown,충청남도,충남,천안시,청룡동,청룡동,False,3
21639,2020-04-26 23:01:06,19,10,406,1,충청남도 천안시 동남구 청룡동,127.173042,36.786983,unknown,충청남도,충남,천안시,청룡동,청룡동,False,3
83980,2021-03-07 18:18:59,19,10,401,1,충청남도 천안시 동남구 청룡동,127.173042,36.786983,Y,충청남도,충남,천안시,청룡동,청룡동,False,3
94114,2021-05-09 19:11:49,19,10,403,3,충청남도 천안시 동남구 청룡동,127.173042,36.786983,unknown,충청남도,충남,천안시,청룡동,청룡동,False,3

In [ ]:
cn.at[98920, 'town2'] = '금마면'

In [100]:
for index, row in cn.iterrows():
  if row['word_town'] == 6:
    cn.at[index, 'town2'] = row['town2'][:3]
  else:
    pass
cn[cn.word_town==6].town2.unique()

array(['신방동', '삼룡동', '다가동', '불당동', '지산동', '사직동', '구성동', '옥룡동', '강산동',
       '부창동', '구룡동', '백석동', '예천동', '석림동', '금성동', '문화동', '청당동', '취암동',
       '신부동', '봉명동', '신관동', '읍내동', '금암동', '와촌동', '갈산동', '산성동'],
      dtype=object)

In [125]:
cn[cn.word_town==7].town2.unique()

array(['읍내동당진1동', '수청동당진1동', '성성동부성2동', '화산동대천3동', '신당동부성1동', '두정동부성1동',
       '성정동성정2동', '권곡동온양3동', '대천동대천2동', '원당동당진3동', '동대동대천3동', '성정동성정1동',
       '원성동원성2동', '쌍용동쌍용1동', '두정동부성2동', '풍기동온양6동', '시곡동당진3동', '용화동온양5동',
       '채운동당진2동', '점양동온양4동', '모종동온양3동', '온천동온양1동', '신흑동대천5동', '좌부동온양6동',
       '동문동동문1동', '원성동원성1동', '온천동온양2동', '기산동온양5동', '쌍용동쌍용3동', '차암동부성2동',
       '실옥동온양4동', '남곡동대천5동', '잠홍동동문1동', '득산동온양4동', '쌍용동쌍용2동', '동문동동문2동',
       '장존동온양6동'], dtype=object)

In [126]:
cn[cn.town2=='당진동']

Empty DataFrame
Columns: [RECV_CPLT_DM, NPA_CL, EVT_STAT_CD, EVT_CL_CD, RPTER_SEX, HPPN_PNU_ADDR, HPPN_X, HPPN_Y, SME_EVT_YN, ADDR1, state, city, town, town2, is_town, word_town]
Index: []

In [110]:
cn['town2'] = cn['town2'].replace('내동행정취암동', '취암동')

In [122]:
cn[(cn.town2=='취암동') & (cn.word_town==7)]

Empty DataFrame
Columns: [RECV_CPLT_DM, NPA_CL, EVT_STAT_CD, EVT_CL_CD, RPTER_SEX, HPPN_PNU_ADDR, HPPN_X, HPPN_Y, SME_EVT_YN, ADDR1, state, city, town, town2, is_town, word_town]
Index: []

In [121]:
for i in [32103, 32633, 32763, 32888, 33055, 33076]:
  cn.at[i, 'word_town'] = 3

In [ ]:
cn[(cn.town2=='취암동') & (cn.word_town==7)]

In [ ]:
cn['town2'] = cn['town2'].replace('8', '취암동')

In [123]:
cn[cn['town']=='중동행정중학동']

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2,is_town,word_town
32824,2020-06-15 16:11:01,19,10,401,1,충청남도 공주시 중동행정중학동 180,127.124091,36.453675,unknown,충청남도,충남,공주시,중동행정중학동,중동행정중학동,True,7

In [124]:
cn.at[32824,'town2'] = '중학동'
cn.at[32824,'word_town'] = '3'

In [128]:
for index, row in cn.iterrows():
  if row['word_town'] == 7:
    cn.at[index, 'town2'] = row['town2'][-4:]
  else:
    pass
cn[cn.word_town==7].town2.unique()

array(['당진1동', '부성2동', '대천3동', '부성1동', '성정2동', '온양3동', '대천2동', '당진3동',
       '성정1동', '원성2동', '쌍용1동', '온양6동', '온양5동', '당진2동', '온양4동', '온양1동',
       '대천5동', '동문1동', '원성1동', '온양2동', '쌍용3동', '쌍용2동', '동문2동'],
      dtype=object)

In [129]:
cn[cn.word_town==8].town2.unique()

array(['신관동행정신관동', '봉명동행정봉명동', '읍내동행정부춘동', '청당동행정청룡동', '반월동행정취암동',
       '불당동행정불당동', '다가동행정일봉동', '석남동행정석남동', '영성동행정중앙동', '소학동행정옥룡동',
       '산성동행정웅진동', '중학동행정중학동', '예천동행정석남동', '석림동행정수석동', '신부동행정신안동',
       '사직동행정중앙동', '신방동행정신방동', '백석동행정백석동', '대흥동행정중앙동', '검상동행정금학동',
       '월송동행정월송동', '구성동행정청룡동', '대교동행정부창동', '삼룡동행정청룡동', '반죽동행정중학동',
       '강산동행정부창동', '와촌동행정봉명동', '옥룡동행정옥룡동', '수석동행정수석동', '용곡동행정일봉동',
       '취암동행정취암동', '문화동행정문성동', '금흥동행정월송동', '법곡동행정온6동', '양대동행정석남동',
       '청수동행정청룡동', '화지동행정취암동', '부창동행정부창동', '등화동행정부창동', '금성동행정웅진동',
       '웅진동행정웅진동', '금암동행정금암동'], dtype=object)

In [131]:
for index, row in cn.iterrows():
  if row['word_town'] == 8:
    cn.at[index, 'town2'] = row['town2'][-3:]
  else:
    pass
cn[cn.word_town==8].town2.unique()

array(['신관동', '봉명동', '부춘동', '청룡동', '취암동', '불당동', '일봉동', '석남동', '중앙동',
       '옥룡동', '웅진동', '중학동', '수석동', '신안동', '신방동', '백석동', '금학동', '월송동',
       '부창동', '문성동', '온6동', '금암동'], dtype=object)

In [132]:
cn[cn.town2=='온6동'] #정온6동으로

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2,is_town,word_town
32315,2020-06-13 10:44:47,19,10,401,1,충청남도 아산시 법곡동행정온6동,127.012487,36.764448,unknown,충청남도,충남,아산시,법곡동행정온6동,온6동,True,8

In [133]:
cn.at[32315,'town2'] = '정온6동'

In [134]:
cn[cn.word_town==9].town2.unique()

array(['죽정동행정대천1동', '성정동행정성정2동', '원성동행정원성2동', '남곡동행정대천5동', '모종동행정온양3동',
       '화산동행정대천3동', '두정동행정부성2동', '성정동행정성정1동', '대천동행정대천2동', '궁촌동행정대천4동',
       '시곡동행정당진3동', '동대동행정대천3동', '용화동행정온양5동', '쌍용동행정쌍용3동', '두정동행정부성1동',
       '풍기동행정온양6동', '쌍용동행정쌍용2동', '쌍용동행정쌍용1동', '권곡동행정온양3동', '동문동행정동문1동',
       '원성동행정원성1동', '방축동행정온양4동', '읍내동행정당진1동', '동문동행정동문2동', '실옥동행정온양4동',
       '차암동행정부성2동', '온천동행정온양2동', '온천동행정온양1동', '신흑동행정대천5동', '실옥동행정온양1동',
       '성성동행정부성2동', '대천동행정대천3동', '채운동행정당진2동', '신당동행정부성1동', '명천동행정대천4동',
       '대천동행정대천4동', '원당동행정당진3동', '잠홍동행정동문1동', '장존동행정온양6동', '득산동행정온양4동',
       '읍내동행정온양6동'], dtype=object)

In [135]:
for index, row in cn.iterrows():
  if row['word_town'] == 9:
    cn.at[index, 'town2'] = row['town2'][-4:]
  else:
    pass
cn[cn.word_town==9].town2.unique()

array(['대천1동', '성정2동', '원성2동', '대천5동', '온양3동', '대천3동', '부성2동', '성정1동',
       '대천2동', '대천4동', '당진3동', '온양5동', '쌍용3동', '부성1동', '온양6동', '쌍용2동',
       '쌍용1동', '동문1동', '원성1동', '온양4동', '당진1동', '동문2동', '온양2동', '온양1동',
       '당진2동'], dtype=object)

In [137]:
cn.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2,is_town,word_town
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남,공주시,정안면,정안면,False,3
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남,논산시,채운면,채운면,False,3
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남,천안시,불당동(불당동),불당동,False,3
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남,천안시,목천읍,목천읍,False,3
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남,서산시,읍내동(부춘동),읍내동,False,3

In [138]:
cn.city.unique()

array(['공주시', '논산시', '천안시', '서산시', '당진시', '아산시', '홍성군', '보령시', '부여군',
       '예산군', '서천군', '태안군', '청양군', '계룡시', '금산군', '당진군'], dtype=object)

In [143]:
cn.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town,town2,is_town,word_town
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남,공주시,정안면,정안면,False,3
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남,논산시,채운면,채운면,False,3
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남,천안시,불당동(불당동),불당동,False,3
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남,천안시,목천읍,목천읍,False,3
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남,서산시,읍내동(부춘동),읍내동,False,3

In [ ]:
cn.drop('town', axis=1, inplace=True)
cn.drop('is_town', axis=1, inplace=True)
cn.drop('word_town', axis=1, inplace=True)
cn['town'] = cn['town2']

In [146]:
cn.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town2
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남,공주시,정안면
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남,논산시,채운면
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남,천안시,불당동
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남,천안시,목천읍
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남,서산시,읍내동

In [149]:
cn.rename({'town2':'town'}, inplace=True)
cn.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town2
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남,공주시,정안면
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남,논산시,채운면
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남,천안시,불당동
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남,천안시,목천읍
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남,서산시,읍내동

In [150]:
towns = cn.town2
towns

0         정안면
1         채운면
2         불당동
3         목천읍
4         읍내동
         ...
106907    신관동
106908    성남면
106909    시곡동
106910    해미면
106911    홍성읍
Name: town2, Length: 106907, dtype: object

In [151]:
cn.drop('town2',axis=1, inplace=True)
cn.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남,공주시
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남,논산시
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남,천안시
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남,천안시
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남,서산시

In [152]:
cn['town'] = towns

In [153]:
cn.head()

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,ADDR1,state,city,town
0,2020-01-01 00:03:11,19,10,406,1,충청남도 공주시 정안면 어물리(정안면) 33-2,127.148714,36.605751,Y,충청남도,충남,공주시,정안면
1,2020-01-01 00:18:08,19,10,403,1,충청남도 논산시 채운면 장화리(채운면) 533,127.030921,36.164643,unknown,충청남도,충남,논산시,채운면
2,2020-01-01 00:20:04,19,10,402,1,충청남도 천안시 서북구 불당동(불당동) 204-4,127.109667,36.815468,unknown,충청남도,충남,천안시,불당동
3,2020-01-01 00:29:48,19,10,403,1,충청남도 천안시 동남구 목천읍 삼성리(목천읍) 203-19,127.170556,36.762500,unknown,충청남도,충남,천안시,목천읍
4,2020-01-01 00:32:03,19,10,406,1,충청남도 서산시 읍내동(부춘동) 585-1,126.444094,36.786189,unknown,충청남도,충남,서산시,읍내동

In [154]:
cn.to_csv("/content/drive/MyDrive/esaa_data/지역 치안 안전 데이터 분석/충남1.csv")

In [142]:
for i in ['공주시', '논산시', '천안시', '서산시', '당진시', '아산시', '홍성군', '보령시', '부여군','예산군', '서천군', '태안군', '청양군', '계룡시', '금산군', '당진군']:
  towns = cn[cn.city==i].town2.unique()
  print(i)
  print(towns)
  print()

공주시
['정안면' '웅진동' '신관동' '유구읍' '산성동' '계룡면' '반포면' '월송동' '우성면' '금학동' '중학동' '금흥동'
 '옥룡동' '월미동' '금성동' '상왕동' '탄천면' '의당면' '송선동' '동현동' '신풍면' '신기동' '반죽동' '사곡면'
 '이인면' '봉황동' '석장리동' '태봉동' '봉정동' '무릉동' '검상동' '쌍신동' '교동' '소학동' '오곡동' '주미동']

논산시
['채운면' '광석면' '강경읍' '노성면' '취암동' '벌곡면' '연산면' '지산동' '강산동' '연무읍' '화지동' '반월동'
 '양촌면' '대교동' '부창동' '가야곡면' '부적면' '은진면' '관촉동' '상월면' '성동면' '등화동' '덕지동']

천안시
['불당동' '목천읍' '안서동' '신방동' '봉명동' '성정동' '삼룡동' '두정동' '문화동' '수신면' '목천면' '직산읍'
 '쌍용동' '와촌동' '청수동' '성남면' '신부동' '다가동' '성성동' '성거읍' '병천면' '용곡동' '구성동' '차암동'
 '대흥동' '북면' '백석동' '성환읍' '구룡동' '풍세면' '성황동' '원성동' '입장면' '광덕면' '청당동' '신당동'
 '동면' '영성동' '오룡동' '사직동' '부대동' '업성동' '유량동' '청룡동' '성정2동' '원성2동' '부성2동'
 '성정1동' '부성1동' '쌍용3동' '일봉동' '중앙동' '쌍용2동' '쌍용1동' '신안동' '원성1동' '문성동']

서산시
['읍내동' '석남동' '석림동' '지곡면' '팔봉면' '운산면' '해미면' '고북면' '부석면' '동문동' '대산읍' '예천동'
 '음암면' '잠홍동' '인지면' '수석동' '성연면' '갈산동' '죽성동' '장동' '덕지천동' '양대동' '온석동' '부춘동'
 '동문1동' '동문2동' '오남동']

당진시
['우두동' '석문면' '송산면' '우강면' '합덕읍' '읍내동' '신평면' '정미면' '송악읍' '채운동' '원당동' '수청동'
 '순성면' '면천면' '행정동' '시곡동' '대덕동' '고대면' '대호지면' '사기소동' '구룡동' '용연동' '당진1동'
 '당진3동' '당진2동']

아산시
['탕정면' '도고면' '온천동' '둔포면' '신창면' '배방읍' '용화동' '음봉면' '좌부동' '권곡동' '인주면' '모종동'
 '방축동' '염치읍' '풍기동' '송악면' '영인면' '배미동' '법곡동' '실옥동' '기산동' '장존동' '득산동' '선장면'
 '초사동' '읍내동' '남동' '신인동' '신동' '점양동' '온양3동' '온양5동' '온양6동' '온양4동' '온양1동'
 '온양2동' '정온6동']

홍성군
['홍성읍' '홍북읍' '홍북면' '금마면' '광천읍' '구항면' '서부면' '갈산면' '은하면' '결성면' '홍동면' '장곡면']

보령시
['신흑동' '성주면' '명천동' '죽정동' '남포면' '대천동' '동대동' '천북면' '주교면' '궁촌동' '웅천읍' '청소면'
 '남곡동' '주포면' '내항동' '오천면' '주산면' '화산동' '미산면' '요암동' '청라면' '대천1동' '대천5동'
 '대천3동' '대천2동' '대천4동']

부여군
['홍산면' '초촌면' '부여읍' '규암면' '장암면' '석성면' '은산면' '남면' '옥산면' '구룡면' '외산면' '임천면'
 '세도면' '내산면' '양화면' '충화면']

예산군
['응봉면' '신암면' '덕산면' '삽교읍' '신양면' '예산읍' '대술면' '봉산면' '오가면' '고덕면' '대흥면' '광시면']

서천군
['서면' '서천읍' '화양면' '장항읍' '비인면' '마서면' '한산면' '기산면' '시초면' '판교면' '종천면' '마산면'
 '문산면']

태안군
['안면읍' '태안읍' '근흥면' '소원면' '원북면' '이원면' '남면' '고남면']

청양군
['목면' '청양읍' '화성면' '정산면' '남양면' '비봉면' '운곡면' '대치면' '청남면' '장평면']

계룡시
['신도안면' '엄사면' '금암동' '두마면']

금산군
['복수면' '금산읍' '군북면' '금성면' '추부면' '제원면' '진산면' '남일면' '부리면' '남이면']

당진군
['송악면' '면천면' '당진읍']